import { X } from 'lucide-react';
import { itemCategories } from '../../data/mockItems';
import { Divider } from '../ui/Divider';
import { IconButton } from '../ui/IconButton';

export type BrowseFilters = { location: string; availability: string; condition: string; category: string };
type FilterPanelProps = { filters: BrowseFilters; onChange: (filters: BrowseFilters) => void; open: boolean; onClose: () => void };

const options = { availability: ['All', 'Available', 'Borrowed', 'Coming soon'], condition: ['All', 'Like new', 'Good', 'Well loved'] };

export function FilterPanel({ filters, onChange, open, onClose }: FilterPanelProps) {
    const update = (key: keyof BrowseFilters, value: string) => onChange({ ...filters, [key]: value });
    return <><div className={`fixed inset-0 z-40 bg-ink/30 transition-opacity lg:hidden ${open ? 'visible opacity-100' : 'pointer-events-none invisible opacity-0'}`} onClick={onClose} /><aside className={`fixed inset-y-0 left-0 z-50 w-[290px] overflow-y-auto bg-surface p-6 transition-transform lg:static lg:z-auto lg:block lg:w-auto lg:translate-x-0 lg:rounded-card lg:border lg:border-line lg:p-5 ${open ? 'translate-x-0' : '-translate-x-full'}`}><div className="flex items-center justify-between"><h2 className="font-display text-xl font-semibold text-ink">Filter by</h2><IconButton label="Close filters" className="lg:hidden" onClick={onClose}><X size={18} /></IconButton></div><Divider className="my-5" /><label className="block"><span className="mb-2 block text-sm font-semibold text-ink">Location</span><input value={filters.location} onChange={(event) => update('location', event.target.value)} placeholder="Any location" className="h-10 w-full rounded-control border border-line bg-canvas px-3 text-sm outline-none focus:border-sage" /></label><Divider className="my-5" /><fieldset><legend className="mb-3 text-sm font-semibold text-ink">Availability</legend><div className="grid gap-2">{options.availability.map((value) => <label key={value} className="flex items-center gap-2 text-sm text-muted"><input type="radio" name="availability" checked={filters.availability === value} onChange={() => update('availability', value)} className="accent-sage" />{value}</label>)}</div></fieldset><Divider className="my-5" /><fieldset><legend className="mb-3 text-sm font-semibold text-ink">Condition</legend><div className="grid gap-2">{options.condition.map((value) => <label key={value} className="flex items-center gap-2 text-sm text-muted"><input type="radio" name="condition" checked={filters.condition === value} onChange={() => update('condition', value)} className="accent-sage" />{value}</label>)}</div></fieldset><Divider className="my-5" /><fieldset><legend className="mb-3 text-sm font-semibold text-ink">Category</legend><div className="grid gap-2">{['All', ...itemCategories].map((value) => <label key={value} className="flex items-center gap-2 text-sm text-muted"><input type="radio" name="category" checked={filters.category === value} onChange={() => update('category', value)} className="accent-sage" />{value}</label>)}</div></fieldset></aside></>;
}