import { ArrowRight, Check, Leaf, Share2, Sparkles, Users } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '../components/ui/Button';
import { Card } from '../components/ui/Card';
import { CTASection } from '../components/ui/CTASection';

export function HomePage() {
    return <div>
        <section className="mx-auto grid max-w-7xl gap-10 px-6 pb-16 pt-12 sm:pt-16 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:px-10 lg:pb-24 lg:pt-20"><div className="max-w-xl"><p className="font-handwritten text-3xl text-sage">A little less buying, a lot more sharing</p><h1 className="mt-4 font-display text-5xl font-semibold leading-[1.05] text-ink sm:text-6xl">Before you buy it, see if you can <span className="text-bark">borrow it.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-muted">Find the things you need from people around you. Save money, reduce waste, and keep useful things moving through your community.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/browse"><Button>Find something to borrow <ArrowRight size={17} /></Button></Link><Link to="/signup" className="inline-flex h-11 items-center justify-center rounded-control border border-line px-5 text-sm font-semibold text-ink hover:border-bark hover:text-bark">Join the community</Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-muted"><span className="inline-flex items-center gap-2"><Check size={16} className="text-sage" />Free to join</span><span className="inline-flex items-center gap-2"><Check size={16} className="text-sage" />Neighbors you can trust</span></div></div><div className="relative"><div className="overflow-hidden rounded-[24px] bg-sage-soft"><img src="https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1100&h=850&q=84" alt="Friends sharing a relaxed moment outdoors" className="aspect-[4/3] h-full w-full object-cover" /></div><div className="absolute -bottom-5 left-5 rounded-card border border-line bg-surface p-4 shadow-soft sm:left-8"><div className="flex items-center gap-3"><span className="inline-flex h-9 w-9 items-center justify-center rounded-full bg-sage-soft text-sage"><Leaf size={18} /></span><span><strong className="block font-display text-lg text-ink">2,480</strong><small className="text-xs text-muted">things kept in use</small></span></div></div></div></section>
        <section className="border-y border-line bg-surface"><div className="mx-auto grid max-w-7xl gap-5 px-6 py-12 sm:grid-cols-3 lg:px-10"><Card className="border-0 bg-canvas p-6"><Share2 className="text-sage" size={22} /><h2 className="mt-5 font-display text-xl font-semibold">Access, not ownership</h2><p className="mt-2 text-sm leading-6 text-muted">Get what you need for the moment without adding another rarely-used thing to your home.</p></Card><Card className="border-0 bg-canvas p-6"><Users className="text-sage" size={22} /><h2 className="mt-5 font-display text-xl font-semibold">Your community, closer</h2><p className="mt-2 text-sm leading-6 text-muted">Borrow from neighbors, meet people nearby, and make sharing feel simple and safe.</p></Card><Card className="border-0 bg-canvas p-6"><Leaf className="text-sage" size={22} /><h2 className="mt-5 font-display text-xl font-semibold">A lighter footprint</h2><p className="mt-2 text-sm leading-6 text-muted">Every shared item is one less purchase and one more useful life for something already made.</p></Card></div></section>
        <section className="mx-auto max-w-7xl px-6 py-16 lg:px-10 lg:py-24"><div className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-sage">How it works</p><h2 className="mt-3 font-display text-4xl font-semibold leading-tight">The better question is often closer than you think.</h2></div><div className="grid gap-6 sm:grid-cols-3"><div><span className="font-handwritten text-3xl text-sage">01</span><h3 className="mt-3 font-display text-xl font-semibold">Say what you need</h3><p className="mt-2 text-sm leading-6 text-muted">Search for an item or tell the community what would help.</p></div><div><span className="font-handwritten text-3xl text-sage">02</span><h3 className="mt-3 font-display text-xl font-semibold">Find it nearby</h3><p className="mt-2 text-sm leading-6 text-muted">Browse real items shared by people in your area.</p></div><div><span className="font-handwritten text-3xl text-sage">03</span><h3 className="mt-3 font-display text-xl font-semibold">Share it forward</h3><p className="mt-2 text-sm leading-6 text-muted">When you have something useful, let someone else borrow it.</p></div></div></div></section>
        <section className="bg-sage-soft"><div className="mx-auto grid max-w-7xl gap-8 px-6 py-14 sm:grid-cols-3 lg:px-10"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-sage">Our shared impact</p><p className="mt-3 font-display text-4xl font-semibold text-ink">348</p><p className="mt-1 text-sm text-muted">neighbors sharing locally</p></div><div><p className="mt-5 font-display text-4xl font-semibold text-ink sm:mt-0">2,480</p><p className="mt-1 text-sm text-muted">items kept in use</p></div><div><p className="mt-5 font-display text-4xl font-semibold text-ink sm:mt-0">1.2t</p><p className="mt-1 text-sm text-muted">estimated waste avoided</p></div></div></section>
        <section className="mx-auto max-w-7xl px-6 py-16 lg:px-10 lg:py-24"><CTASection title="The next thing you need might already be here." description="Start with a search. Stay for the community." /></section>
    </div>;
}