import { Check, CircleHelp, Leaf } from 'lucide-react';
import type { AccessMethod } from '../../../shared/types/accessOptions';
import type { RecommendationExplanation, RecommendationReasonCode, RecommendationResult } from '../../../shared/types/recommendation';
import { AccessOptionCard } from './AccessOptionCard';
import { Badge } from '../ui/Badge';
import { Card } from '../ui/Card';

const methodLabels: Record<AccessMethod, string> = { borrow: 'Borrow', rent: 'Rent', 'buy-used': 'Buy Used', 'buy-new': 'Buy New' };
const reasonLabels: Record<RecommendationReasonCode, string> = {
    one_time_use: 'Matches your one-time usage', frequent_use: 'Fits your expected regular use', low_total_cost: 'Has the lowest modeled total cost', low_cost_per_use: 'Has the lowest modeled cost per use', nearby: 'Close to your location', high_trust: 'Trusted provider', available: 'Available when you need it', strong_capability_match: 'Matches your required capabilities', within_budget: 'Within your stated budget', ownership_economical: 'Ownership is not necessary for this usage', borrowing_available: 'A borrowing option is available', rental_more_economical: 'Rental is more economical in this model', used_purchase_more_economical: 'Used purchase is more economical in this model', new_purchase_more_suitable: 'New purchase has the strongest condition fit',
};
const currency = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });

function money(value: number | null) {
    return value === null ? 'Not available' : currency.format(value);
}

export function RecommendationPanel({ result, explanation }: { result: RecommendationResult; explanation: RecommendationExplanation | null }) {
    const ownership = result.ownershipComparison;
    return <section className="mt-12 border-t border-line pt-10">
        <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-sage">Your access recommendation</p><h2 className="mt-2 font-display text-4xl font-semibold text-ink">A thoughtful way to access it</h2><p className="mt-2 text-sm text-muted">This is a deterministic recommendation based on your requirement, available options, scores, and modeled usage.</p></div><Badge tone="sage">{methodLabels[result.recommendationType]}</Badge></div>
        <AccessOptionCard option={result.recommendedOption} />
        <div className="mt-5 grid gap-4 sm:grid-cols-3"><Card className="p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted">Confidence</p><p className="mt-2 font-display text-3xl font-semibold text-bark">{Math.round(result.confidence)}<span className="text-base text-muted">/100</span></p></Card><Card className="p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted">Estimated savings</p><p className="mt-2 font-display text-2xl font-semibold text-bark">{money(result.estimatedSavings)}</p><p className="mt-1 text-xs text-muted">Compared with the modeled new-purchase baseline.</p></Card><Card className="p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-muted">Access score</p><p className="mt-2 font-display text-3xl font-semibold text-bark">{Math.round(result.accessScore)}<span className="text-base text-muted">/100</span></p></Card></div>
        <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_1.1fr]"><Card className="p-6"><h3 className="font-display text-2xl font-semibold text-ink">Why this recommendation</h3><ul className="mt-5 grid gap-3">{result.reasonCodes.map((reason) => <li key={reason} className="flex items-start gap-2 text-sm text-ink"><Check size={17} className="mt-0.5 shrink-0 text-sage" />{reasonLabels[reason]}</li>)}</ul>{explanation ? <div className="mt-6 border-t border-line pt-5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-sage"><CircleHelp size={15} />Explanation · {explanation.source}</div><p className="mt-2 text-sm leading-6 text-muted">{explanation.explanation}</p></div> : null}</Card><Card className="p-6"><div className="flex items-center gap-2"><Leaf size={19} className="text-sage" /><h3 className="font-display text-2xl font-semibold text-ink">Do you need to own it?</h3></div><p className="mt-2 text-xs text-muted">Estimated ownership economics based on expected usage, not a guaranteed financial outcome.</p><dl className="mt-5 grid gap-4 sm:grid-cols-2"><div><dt className="text-xs text-muted">Expected usage</dt><dd className="mt-1 font-semibold text-ink">{ownership.expectedUses} uses · {ownership.expectedUsageLabel}</dd></div><div><dt className="text-xs text-muted">Estimated ownership cost</dt><dd className="mt-1 font-semibold text-ink">{money(ownership.totalOwnershipCost)}</dd></div><div><dt className="text-xs text-muted">Estimated rental cost</dt><dd className="mt-1 font-semibold text-ink">{money(ownership.estimatedRentalCost)}</dd></div><div><dt className="text-xs text-muted">Borrowing cost</dt><dd className="mt-1 font-semibold text-ink">{money(ownership.borrowingCost)}</dd></div><div><dt className="text-xs text-muted">Ownership cost per use</dt><dd className="mt-1 font-semibold text-ink">{money(ownership.ownershipCostPerUse)}</dd></div><div><dt className="text-xs text-muted">Ownership necessity</dt><dd className="mt-1 font-semibold text-ink">{Math.round(ownership.ownershipNecessityScore)}/100</dd></div></dl></Card></div>
        <Card className="mt-5 overflow-hidden"><div className="p-6"><h3 className="font-display text-2xl font-semibold text-ink">Compare access methods</h3><p className="mt-2 text-sm text-muted">Modeled total cost and access score for the available candidates.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[540px] text-left text-sm"><thead className="border-y border-line bg-canvas text-xs uppercase tracking-[0.12em] text-muted"><tr><th className="px-6 py-3 font-semibold">Method</th><th className="px-6 py-3 font-semibold">Total cost</th><th className="px-6 py-3 font-semibold">Access score</th></tr></thead><tbody>{(['borrow', 'rent', 'buy-used', 'buy-new'] as const).map((method) => { const comparison = ownership.comparison.find((item) => item.accessMethod === method); const scored = result.rankedOptions.filter((item) => item.accessMethod === method).sort((left, right) => right.finalScore - left.finalScore)[0]; return <tr key={method} className="border-b border-line last:border-b-0"><td className="px-6 py-4 font-semibold text-ink">{methodLabels[method]}{method === result.recommendationType ? <span className="ml-2 text-xs font-normal text-sage">selected</span> : null}</td><td className="px-6 py-4 text-muted">{money(comparison?.totalCost ?? null)}</td><td className="px-6 py-4 font-semibold text-bark">{scored ? `${Math.round(scored.finalScore)}/100` : 'Not available'}</td></tr>; })}</tbody></table></div></Card>
    </section>;
}